### ISSUE TITLE
Period input being swallowed

### ISSUE THREAD

**Issue by metamaterialsuit** [chase/awrit#24]
First of all, incredibly  impressed at how well this works.

Was wondering, has anyone run into an issue inputting a "period" into a form? For instance, I've tried to enter my email address which uses periods as delimiters and the only way that it seems to work is by using windowskey + period (I'm on ubuntu)

**Comment by chase** [comment]
What an odd bug. :joy: Not sure how I missed that!

Stranger is that `tty/input_event_test.cc` seems to detect `.` just fine, so whatever way it's being sent to Chromium isn't what it expects.
