### ISSUE TITLE
macOS build error 

### ISSUE THREAD

**Issue by noahlias** [chase/awrit#30]
![image](https://github.com/chase/awrit/assets/3949397/e1b50e3d-8285-41eb-8163-ffe25c246162)

```
λ brew list --versions |egrep '(cmake|ninja)'
cmake 3.28.1
ninja 1.11.1
(base) 
awrit on  main via 🅒 base 
λ xcodebuild -version 
Xcode 15.2
Build version 15C500b
```

**Comment by chase** [comment]
Please see https://github.com/chase/awrit/issues/27

**Comment by chase** [comment]
I updated the readme to be more clear, but for now, try using xcodes to install and use Xcode 14.3 to build:
https://github.com/XcodesOrg/xcodes
