### ISSUE TITLE
Realse config on Mac needed

### ISSUE THREAD

**Issue by bahman777** [chase/awrit#31]
Cannot install on Mac. Need a Realse configuration. Is it possible to get a brew binary?

Thanks

**Comment by chase** [comment]
Sorry, I'm not sure I understand the issue. You'll need to build it yourself to get a release: https://github.com/chase/awrit#building

Please ensure you install all the prerequisites before building.

There are no binary releases and `brew` does not gracefully handle multiple versions of Xcode, so you'll have to wait until M1 macOS runners are generally available for open source projects.

Please see this issue for more information: https://github.com/chase/awrit/issues/27

**Comment by bahman777** [comment]
Thank you. My issue with Xcode. Already built it. Great browser. Any docs on keys and usage?

**Comment by chase** [comment]
> Thank you. My issue with Xcode. Already built it. Great browser. Any docs on keys and usage?

The README explains the usage.

Keys should be the same defaults in Chromium.
