### ISSUE TITLE
Awesome browser

### ISSUE THREAD

**Issue by bahman777** [chase/awrit#34]
Love this project and browser. Thank you. I just wished I could figure out how to use it effectively. Can't figure out the keys (like how to quit or go previous page) etc.

**Comment by chase** [comment]
Bahman, thanks for your kind words. #4 is not complete but as I said in the other issue you created, the keys are the same as Chromium's keys.

Quitting is the same as most other terminal apps: ctrl-c

You can try `Alt/Option+Left` for back and `Alt/Option+Right` for forward. These may not work I'd your OS overrides them.
