### ISSUE TITLE
Resizing a windows doesn't work

### ISSUE THREAD

**Issue by GustavoJCL** [chase/awrit#38]
Hi, when i tried to resize my kitty windows it just show a dark bar instead of resizing the page
![image](https://github.com/chase/awrit/assets/93671143/e2dc5509-48f7-40c7-b3f6-61a09133a7db)

**Comment by chase** [comment]
Thanks for reporting.

Please make one issue per problem/feature request in the future. I've split the video support problem into another issue.

**Comment by chase** [comment]
This is actually a duplicate of https://github.com/chase/awrit/issues/8
